enum ErrorMsg {
  NOT_FOUND = "NOT FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD REQUEST",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_WRONG_CREDENTIALS = "USER_WRONG_CREDENTIAL",
  REQUIRE_AUTHENTICATION = "REQUIRE_AUTHENTICATION",
  NETWORK_AUTHENTICATION_REQUIRED = "NETWORK_AUTHENTICATION_REQUIRED",
}

export default ErrorMsg;
